on:
  workflow_dispatch:
  schedule:
    - cron: 45 19 * * *
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.19.3
      - run: |
          curl -L http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest \
            | awk -F'|' '
              $1 == "apnic" && $2 == "CN" {
                if ($3 == "ipv4")
                  printf("%s/%d\n", $4, 32-log($5)/log(2))
                else if ($3 == "ipv6")
                  printf("%s/%s\n", $4, $5)
              }
            ' >ips
          mkdir public
          go run . ips public/cnip.mmdb
      - uses: actions/upload-pages-artifact@v1
        with:
          path: "public"
      - uses: actions/deploy-pages@v1
